package com.newplanner.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.util.List;

@Entity
@Table(name = "itinerary_days")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ItineraryDay {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @com.fasterxml.jackson.annotation.JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "itinerary_id", nullable = false)
    private Itinerary itinerary;

    @Column(nullable = false)
    private Integer dayNumber; // 1, 2, 3...

    @Column(nullable = false)
    private LocalDate date;

    private String theme; // Generated by AI (e.g., "Historical Deep Dive")

    private Double estimatedCost; // AI-assigned dynamic cost estimate for this specific day


    @OneToMany(mappedBy = "day", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @OrderBy("startTime ASC")
    private List<Activity> activities;
}
